id: counter-test
name: Counter Test
version: 1
description: |
  Dead-simple orchestration test. Three agents each add 1 to a number.
  Start: 0 → Agent A outputs 1 → Agent B outputs 2 → Agent C outputs 3.
  If the final number is 3, the pipeline works.

context:
  number: "0"

agents:
  - id: adder-a
    name: Adder A
    description: Adds 1 to the input number.
    workspace:
      baseDir: agents/adder
      files:
        AGENTS.md: agents/adder/AGENTS.md
        IDENTITY.md: agents/adder/IDENTITY.md
        SOUL.md: agents/adder/SOUL.md

  - id: adder-b
    name: Adder B
    description: Adds 1 to the input number.
    workspace:
      baseDir: agents/adder
      files:
        AGENTS.md: agents/adder/AGENTS.md
        IDENTITY.md: agents/adder/IDENTITY.md
        SOUL.md: agents/adder/SOUL.md

  - id: adder-c
    name: Adder C
    description: Adds 1 to the input number.
    workspace:
      baseDir: agents/adder
      files:
        AGENTS.md: agents/adder/AGENTS.md
        IDENTITY.md: agents/adder/IDENTITY.md
        SOUL.md: agents/adder/SOUL.md

steps:
  - id: add-first
    agent: adder-a
    input: |
      You are a counter agent. Your ONLY job is to add 1 to a number.

      INPUT_NUMBER: {{number}}

      Instructions:
      1. Take the INPUT_NUMBER
      2. Add 1 to it
      3. Reply with EXACTLY this format (nothing else):

      STATUS: done
      NUMBER: <the new number>
    expects: "STATUS: done"
    on_fail:
      escalate_to: human

  - id: add-second
    agent: adder-b
    input: |
      You are a counter agent. Your ONLY job is to add 1 to a number.

      INPUT_NUMBER: {{number}}

      Instructions:
      1. Take the INPUT_NUMBER
      2. Add 1 to it
      3. Reply with EXACTLY this format (nothing else):

      STATUS: done
      NUMBER: <the new number>
    expects: "STATUS: done"
    on_fail:
      escalate_to: human

  - id: add-third
    agent: adder-c
    input: |
      You are a counter agent. Your ONLY job is to add 1 to a number.

      INPUT_NUMBER: {{number}}

      Instructions:
      1. Take the INPUT_NUMBER
      2. Add 1 to it
      3. Reply with EXACTLY this format (nothing else):

      STATUS: done
      NUMBER: <the new number>
    expects: "STATUS: done"
    on_fail:
      escalate_to: human
